### ISSUE TITLE
Sugestion

### ISSUE THREAD

**Issue by aureliocarnero** [joezuntz/2point#1]
Hello!
I wanted to share with you a question I had, and it is how could we deal with a multiple redshift bins analysis. I thought about it because we will have to deal with convariance matrices between redshift bins. I dont know if that is out of the scope of this code, but maybe, we could thing something in the line of allowing many redshift bins 2point data in the same file, stating in the header the number of bins and then, 2PTDATA_1, 2PTDATA_2... in the case than more than one. Also with NZDATA and COVDATA. And finally, a global nzdata and the global covariance matrix between the redshift bins. Which sufix I dont know.. 
Maybe you have thought about this already, but since I didnt see anything in the readme, I thought it could be useful. 
Thank you!

**Comment by NiallMac** [comment]
Hi Aurelio,

Multiple redshift bins are already supported. See e.g. bin1 and bin2
attributes of the SpectrumMeasurement class, which index the two redshift
bins associated with any angular two-point measurement.

The covariance matrix is just stored as single matrix with the ordering
matching the ordering of the SpectrumMeasurement instances in the
TwoPointFile 'spectra' attribute. The covariance between redshift bins (and
between different spectra) is therefore accounted for.

Niall

**Comment by aureliocarnero** [comment]
Great! Im glad, thank you. I will play with the code and give you feedback if I find something striking.
Cheers, great work
